import {
  Activity,
  Bot,
  CheckCircle2,
  FileText,
  Mail,
  Sparkles,
  UserRoundCheck,
  Workflow,
} from "lucide-react";
import { demoActivity } from "../data/demo";

const icons = {
  Candidate: FileText,
  "AI System": Sparkles,
  Automation: Bot,
  Recruiter: UserRoundCheck,
} as const;

const actorStyles = {
  Candidate: {
    badge: "bg-slate-100 text-slate-700",
    icon: "bg-slate-100 text-slate-700",
  },
  "AI System": {
    badge: "bg-violet-50 text-violet-700",
    icon: "bg-violet-100 text-violet-700",
  },
  Automation: {
    badge: "bg-sky-50 text-sky-700",
    icon: "bg-sky-100 text-sky-700",
  },
  Recruiter: {
    badge: "bg-emerald-50 text-emerald-700",
    icon: "bg-emerald-100 text-emerald-700",
  },
} as const;

export function ActivityPage() {
  const candidateEvents = demoActivity.filter(
    (event) => event.actor === "Candidate",
  ).length;

  const aiEvents = demoActivity.filter(
    (event) => event.actor === "AI System",
  ).length;

  const automationEvents = demoActivity.filter(
    (event) => event.actor === "Automation",
  ).length;

  const recruiterEvents = demoActivity.filter(
    (event) => event.actor === "Recruiter",
  ).length;

  return (
    <div className="space-y-6">
      {/* HERO */}

      <section className="relative overflow-hidden rounded-2xl border border-slate-800 bg-[#070b18] px-6 py-7 text-white shadow-xl shadow-slate-900/5 sm:px-7">
        <div className="pointer-events-none absolute inset-0 opacity-60 [background-image:radial-gradient(circle_at_12%_12%,rgba(124,58,237,0.30)_0,transparent_28%),radial-gradient(circle_at_88%_16%,rgba(14,165,233,0.18)_0,transparent_24%)]" />

        <div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-1.5 text-xs font-semibold text-violet-200">
              <Activity className="h-3.5 w-3.5" />
              Recruitment Audit Trail
            </div>

            <h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">
              Activity
            </h1>

            <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">
              Auditable hiring events across candidates, AI screening,
              workflow automation, and recruiter decisions.
            </p>
          </div>

          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <HeaderMetric
              label="Candidate"
              value={candidateEvents}
            />

            <HeaderMetric
              label="AI"
              value={aiEvents}
            />

            <HeaderMetric
              label="Automation"
              value={automationEvents}
            />

            <HeaderMetric
              label="Recruiter"
              value={recruiterEvents}
            />
          </div>
        </div>
      </section>

      {/* OPERATIONAL SUMMARY */}

      <section className="grid gap-4 md:grid-cols-3">
        <OperationalCard
          icon={Workflow}
          title="Workflow Events"
          value={demoActivity.length}
          description="Recorded events across the recruitment pipeline."
        />

        <OperationalCard
          icon={Sparkles}
          title="AI Screening"
          value={aiEvents}
          description="Candidate intelligence events generated by AI."
        />

        <OperationalCard
          icon={CheckCircle2}
          title="Human Decisions"
          value={recruiterEvents}
          description="Recruiter actions recorded in the hiring audit trail."
        />
      </section>

      {/* ACTIVITY TIMELINE */}

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
        <div className="border-b border-slate-100 px-5 py-5">
          <div>
            <p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-violet-600">
              System Timeline
            </p>

            <h2 className="mt-1 text-lg font-semibold text-slate-950">
              Recruitment Activity
            </h2>

            <p className="mt-1 text-xs text-slate-500">
              Chronological system events for visibility and operational
              traceability.
            </p>
          </div>
        </div>

        <div className="p-5 sm:p-6">
          <div className="space-y-6">
            {demoActivity.map((event, index) => {
              const Icon = icons[event.actor];
              const style = actorStyles[event.actor];

              return (
                <div
                  key={event.id}
                  className="relative flex gap-4"
                >
                  {/* TIMELINE ICON */}

                  <div
                    className={`relative z-10 grid h-11 w-11 shrink-0 place-items-center rounded-xl ${style.icon}`}
                  >
                    <Icon className="h-4 w-4" />
                  </div>

                  {/* CONNECTOR */}

                  {index < demoActivity.length - 1 && (
                    <div className="absolute left-[21px] top-11 h-[calc(100%+12px)] w-px bg-slate-200" />
                  )}

                  {/* EVENT CARD */}

                  <div className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 p-4 transition hover:border-slate-300 hover:bg-white">
                    <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
                      <div className="min-w-0">
                        <div className="flex flex-wrap items-center gap-2">
                          <h3 className="text-sm font-semibold text-slate-900">
                            {event.title}
                          </h3>

                          <span
                            className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] ${style.badge}`}
                          >
                            {event.actor}
                          </span>
                        </div>

                        <p className="mt-2 text-sm leading-6 text-slate-500">
                          {event.description}
                        </p>
                      </div>

                      <div className="shrink-0">
                        <p className="font-mono text-[11px] text-slate-400">
                          {new Date(event.timestamp).toLocaleString()}
                        </p>
                      </div>
                    </div>

                    <div className="mt-4 flex flex-wrap items-center gap-4 border-t border-slate-200 pt-3 text-[10px] uppercase tracking-[0.12em] text-slate-400">
                      <span>
                        Event #{event.id}
                      </span>

                      <span className="h-1 w-1 rounded-full bg-slate-300" />

                      <span>
                        Source · {event.actor}
                      </span>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* AUDIT CONTROL */}

      <section className="grid gap-4 md:grid-cols-3">
        <AuditCard
          icon={FileText}
          title="Candidate Events"
          description="Application and resume activity is visible in the timeline."
        />

        <AuditCard
          icon={Bot}
          title="Automation Events"
          description="n8n workflow actions can be represented as operational events."
        />

        <AuditCard
          icon={Mail}
          title="Communication Events"
          description="Candidate email activity can be included for full hiring traceability."
        />
      </section>
    </div>
  );
}

function HeaderMetric({
  label,
  value,
}: {
  label: string;
  value: number;
}) {
  return (
    <div className="min-w-[100px] rounded-xl border border-white/10 bg-white/[0.05] px-4 py-3">
      <p className="text-[9px] font-semibold uppercase tracking-[0.14em] text-slate-500">
        {label}
      </p>

      <p className="mt-1 text-xl font-semibold text-white">
        {value}
      </p>
    </div>
  );
}

function OperationalCard({
  icon: Icon,
  title,
  value,
  description,
}: {
  icon: typeof Workflow;
  title: string;
  value: number;
  description: string;
}) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5">
      <div className="flex items-start justify-between">
        <div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-700">
          <Icon className="h-4 w-4" />
        </div>

        <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide text-emerald-700">
          Recorded
        </span>
      </div>

      <p className="mt-5 text-3xl font-semibold tracking-tight text-slate-950">
        {value}
      </p>

      <p className="mt-2 text-xs font-semibold text-slate-700">
        {title}
      </p>

      <p className="mt-1 text-[11px] leading-5 text-slate-400">
        {description}
      </p>
    </div>
  );
}

function AuditCard({
  icon: Icon,
  title,
  description,
}: {
  icon: typeof FileText;
  title: string;
  description: string;
}) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5">
      <div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-700">
        <Icon className="h-4 w-4" />
      </div>

      <h3 className="mt-4 text-sm font-semibold text-slate-950">
        {title}
      </h3>

      <p className="mt-2 text-xs leading-5 text-slate-500">
        {description}
      </p>
    </div>
  );
}